export const commands = {
    START:          'startt',
    MIRRORTAR:      'mirrorTarr|mt',
    MIRROR:         'mirrorr|m',
    MIRROR_STATUS:  'mirrorStatuss|ms',
    LIST:           'listt|l',
    GET_FOLDER:     'getFolderr|gf',
    CANCEL_MIRROR:  'cancelMirrorr|cm',
    CANCEL_ALL:     'cancelAlll|ca',
    STATS:          'statss',
    GET_LINK:       'getLinkk|gl',
    CLONE:          'clonee|c',
    ID:             'id',
    MF:             'mf',
    TAR:            'tar|t',
    UNZIP_MIRROR:   'unzipMirrorr|um',
    COUT:           'countt|cnt',
    HELP:           'helpp|h',
    AUTHORIZE:      'authorizee|a',
    UNAUTHORIZE:    'unauthorizee|ua',
    RESTART:        'restartt|r',
    YTDL:           'ytdll|y'
};

export const commandsAfter: any = {
    START:          '$',
    MIRRORTAR:      '($| (.+))',
    MIRROR:         '($| (.+))',
    MIRROR_STATUS:  '$',
    LIST:           ' (.+)',
    GET_FOLDER:     '$',
    CANCEL_MIRROR:  '($| (.+))',
    CANCEL_ALL:     '$',
    STATS:          '$',
    GET_LINK:       ' (.+)',
    CLONE:          ' (.+)',
    ID:             '$',
    MF:             '$',
    TAR:            ' (.+)',
    UNZIP_MIRROR:   ' (.+)',
    COUT:           ' (.+)',
    HELP:           '$',
    AUTHORIZE:      '$',
    UNAUTHORIZE:    '$',
    RESTART:        '$',
    YTDL:           ' (.+)'
};